-- MyBible Database Schema for PostgreSQL
-- Automatically executed when PostgreSQL container starts

-- AUTH_USERS Table
CREATE TABLE IF NOT EXISTS AUTH_USERS (
    ID VARCHAR(36) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP,

    CONSTRAINT AUTH_USERS_pk PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AUTH_USERS_EMAIL ON AUTH_USERS(LOWER(EMAIL));
